name: Warning maintainers
on:
  pull_request:
    paths: examples/**
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: about example change
        uses: Poolitzer/notifier-action@master
        with:
          notify-message: Guys, GUYS! Someone changed the example. Think about that before you merge!
          repo-token: ${{ secrets.GITHUB_TOKEN }}
