on:
  pull_request:
    paths: examples/**
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: PR Example
        uses: Poolitzer/notifier-action@master
        with:
          notify-message: GET THE FUCK AWAY FROM THE EXAMPLES
          repo-token: 0608ebc45db6d689ba664fd1df7a99c7dac3cd90
